### ISSUE TITLE
Change name from container to module

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#128]
The name `container` (`webviz` terminology) is not optimal. People related to deployment confuses it with Docker containers (especially since Docker is also used in the stack). 

Change to something else? If so, to what?

- ~Component~ (a "container" consists of one or more Dash/React components... also confusing).
- Element (confusing from a developer point of view perhaps, since element indicates something more fundamental than a composition of components).
- Object.
- Plugin (we are using [plugin entrypoints](https://packaging.python.org/guides/creating-and-discovering-plugins/#using-package-metadata)).
- Other?

**Comment by perolavsvendsen** [comment]
Module? (there are Python modules as well, but probably not a problem)

**Comment by anders-kiaer** [comment]
Another idea from @HansKallekleiv: `dashboard`. We have some "containers" currently that are not dashboards, but they are limited in number. The question is if the number of these will increase or not in the future, if not we can perhaps live with "special cases" like:

```yaml
- title: Some title
  content:
    - markdown: ./some_markdown_file.md
      some_setting: some_setting_for_markdown
    - bannerimage: ./some_picture.png
      height: 500px
    - Some text...
    - pdf: some_pdf_file.pdf
    - Some more text...
    - dashboard: Inplace
      some_setting: some_setting_for_inplace
```

Currently there are three main possibilities left: 🎲 
- `plugin`
- `module`
- `dashboard`

**Comment by anders-kiaer** [comment]
Discussed this issue with @HansKallekleiv today, and we think that maybe **_module_** is the terminology we will go with. Calling everything "plugin" sounds a bit strange/unofficial (especially for users internally in Equinor since [`webviz-subsurface`](https://github.com/equinor/webviz-subsurface) is there as "official" as `webviz-config`), and `dashboard` would either require non-dashboard features to still be called dashboards, or treat them as special cases, which would be nice to avoid from a maintenance and code structure point of view.

cc: @HansKallekleiv @perolavsvendsen

**Comment by anders-kiaer** [comment]
Variable naming/terminology (again) turns out to be difficult. I started on implementing this name change today in `webviz-config` core, and end at best up with e.g. providing error messages like:
```python
if webviz_module not in _get_webviz_modules(python_module):
    raise ParserError(
        f"Python module `{python_module}` does not have a "
        f"Webviz Module named `{webviz_module}`"
    )
```
The code also gets a bit more verbose, prefixing all `module` variable names with either `webviz_` or `python_`.

So then suddenly started thinking about using `feature` instead of `module`, or maybe even remove the naming problem altogether and lift up container/module/feature name to a separate level in the config:
```yaml
pages:
  - title: Some page
    - content: 
      - reservoir_simulation_time_series:
        - ensembles:
          - iter-0
          - iter-1
      - some markdown text
      - banner_image:
        - path: some_path
        - height: 500px
```
😕 TBC
