### ISSUE TITLE
User friendly feedback on wrong indentation

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#178]
E.g. when the user provides
```yaml
- SomePlugin:
  someargument: 42
  someotherargument: 42
```
instead of
```yaml
- SomePlugin:
    someargument: 42
    someotherargument: 42
```
in the configuration file.
