### ISSUE TITLE
User input check wrt. indentation

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-config#356]
```yaml
pages:
 - title: Front page
   content:
    - SomePlugin:
      some_argument: 42
```
will give a runtime error
```
webviz_config._config_parser.ParserError: `SomePlugin` requires the argument `some_argument` in your configuration file.
```
which could be difficult to understand (as the argument is there, but is missing an indentation level).

Add extra runtime input check?
