### ISSUE TITLE
Banner Image does not render

### ISSUE THREAD

**Issue by Vikaparra** [equinor/webviz-config#620]
**Description**

I'm running webviz from Windows 10, and every time I try to use the Banner feature, the image doesn't render, instead, only the title appears on the screen.
When I inspect the element using developer tools in the browser, this is what it shows:

When I'm using the non-portable version:
![nonportableerror](https://user-images.githubusercontent.com/49412404/187479837-f0bcbd58-09b1-448c-8107-97826d8c1f41.png)

When I'm using the portable version:
![portableerror](https://user-images.githubusercontent.com/49412404/187480309-8b9ee71c-032f-4804-850d-0050d268b382.png)

I've tried running in edge and firefox, and it doesn't work in either.
Looking at the '"background-image" of the banner tag, it seems like the '/' is being removed and the image path is not found.

**How to reproduce**
My .yaml file looks like this:
```
options:
  menu:
    show_logo: true
    bar_position: left
    drawer_position: left
    initially_pinned: true
    initially_collapsed: true

# ------------------------------
layout:
  - section: Webviz Boilerplate
    content:
      # ------------------------------

      - page: Front page
        icon: home
        content:
          - This is a `webviz` instance created from a configuration file.
          - Open menu on the left to select page for demo plugins.
          - BannerImage:
              image: ./image.png
              title: My banner image
```

I've tried putting the .png file in "./examples", "./plugins", in the plugin folder, and when I use the portable version, the file is in the "./assets" folder as it should.
